MERGE INTO "ROLE_ENTITY" USING (VALUES 1) I ("ID") ON "ROLE_ENTITY"."ID" = I."ID"
WHEN MATCHED THEN UPDATE SET "CODE" = 'SYSTEM'
WHEN NOT MATCHED THEN INSERT ("ID", "CODE") VALUES (I."ID", 'SYSTEM');

MERGE INTO "ROLE_ENTITY" USING (VALUES 2) I ("ID") ON "ROLE_ENTITY"."ID" = I."ID"
WHEN MATCHED THEN UPDATE SET "CODE" = 'ADMIN'
WHEN NOT MATCHED THEN INSERT ("ID", "CODE") VALUES (I."ID", 'ADMIN');

MERGE INTO "USER_ENTITY" USING (VALUES 1) I ("ID") ON "USER_ENTITY"."ID" = I."ID"
WHEN MATCHED THEN UPDATE SET "ACTIVE" = 1, "LOGIN" = 'system', "PASSWD" = 'system'
WHEN NOT MATCHED THEN INSERT ("ID", "ACTIVE", "LOGIN", "PASSWD") VALUES (I."ID", 1, 'system', 'system');

MERGE INTO "USER_ENTITY" USING (VALUES 2) I ("ID") ON "USER_ENTITY"."ID" = I."ID"
WHEN MATCHED THEN UPDATE SET "ACTIVE" = 1, "LOGIN" = 'admin', "PASSWD" = 'admin'
WHEN NOT MATCHED THEN INSERT ("ID", "ACTIVE", "LOGIN", "PASSWD") VALUES (I."ID", 1, 'admin', 'admin');

MERGE INTO "USER_ENTITY_ROLES" USING (VALUES 1, 1) I ("USER_ENTITY_ID", "ROLES_ID")
ON "USER_ENTITY_ROLES"."USER_ENTITY_ID" = I."USER_ENTITY_ID" AND "USER_ENTITY_ROLES"."ROLES_ID" = I."ROLES_ID"
WHEN NOT MATCHED THEN INSERT ("USER_ENTITY_ID", "ROLES_ID") VALUES (I."USER_ENTITY_ID", I."ROLES_ID");

MERGE INTO "USER_ENTITY_ROLES" USING (VALUES 2, 2) I ("USER_ENTITY_ID", "ROLES_ID")
ON "USER_ENTITY_ROLES"."USER_ENTITY_ID" = I."USER_ENTITY_ID" AND "USER_ENTITY_ROLES"."ROLES_ID" = I."ROLES_ID"
WHEN NOT MATCHED THEN INSERT ("USER_ENTITY_ID", "ROLES_ID") VALUES (I."USER_ENTITY_ID", I."ROLES_ID");

MERGE INTO "RESTAURANT_ENTITY" USING (VALUES 1) I ("ID") ON "RESTAURANT_ENTITY"."ID" = I."ID"
WHEN MATCHED THEN UPDATE SET "ACTIVE" = 1
WHEN NOT MATCHED THEN INSERT ("ID", "ACTIVE", "ADDRESS", "DESCRIPTION", "NAME", "PHONE")
VALUES (I."ID", 1, 'Park ave., 18', NULL, 'Test Restaurant', NULL);

MERGE INTO "MENU_ENTITY" USING (VALUES 1) I ("ID") ON "MENU_ENTITY"."ID" = I."ID"
WHEN MATCHED THEN UPDATE SET "DATE" = CURRENT_DATE, "RESTAURANT_ID" = 1
WHEN NOT MATCHED THEN INSERT ("ID", "DATE", "NAME", "RESTAURANT_ID")
VALUES (I."ID", CURRENT_DATE, 'Business lunch', 1);

MERGE INTO "MENU_ITEM_ENTITY" USING (VALUES 1) I ("ID") ON "MENU_ITEM_ENTITY"."ID" = I."ID"
WHEN NOT MATCHED THEN INSERT ("ID", "NAME", "NUMBER", "PRICE", "ITEMS_ID")
VALUES (I."ID", 'Soup', 0, 2.99, 1);

MERGE INTO "MENU_ITEM_ENTITY" USING (VALUES 2) I ("ID") ON "MENU_ITEM_ENTITY"."ID" = I."ID"
WHEN NOT MATCHED THEN INSERT ("ID", "NAME", "NUMBER", "PRICE", "ITEMS_ID")
VALUES (I."ID", 'Cutlet with rise', 1, 4.99, 1);

MERGE INTO "MENU_ITEM_ENTITY" USING (VALUES 3) I ("ID") ON "MENU_ITEM_ENTITY"."ID" = I."ID"
WHEN NOT MATCHED THEN INSERT ("ID", "NAME", "NUMBER", "PRICE", "ITEMS_ID")
VALUES (I."ID", 'Orange juice', 2, 0.99, 1);